# Commit message convention: "(doc)" means README updates, etc. - they don't change any code.
if: commit_message !~ /^\(doc\)/

dist: trusty
language: php

conditions: v1

git:
  depth: 1

notifications:
  email: false

branches:
  except:
  - REL1_23

services:
  - memcached

addons:
  &common-addons
  hosts:
    - moderation.example.com
  mariadb: "10.3"

php:
  - 7.2

env:
  global:
    - TESTSUITE_TYPE=phpunit
    - DBTYPE=mysql
    - DBUSER=root
    - MEDIAWIKI_USER="Moderator User"
    - MEDIAWIKI_PASSWORD="123456"
    - SAUCE_USERNAME=edwardspec
    - secure: "YzZDIDMvMH4xKsFC9f/Z5algUXnY9kMpBpD0i9k8Iew6ci6mCG73V0t+65MpTcUxLDEExMjjkdnzmKGULw1vgSLwwKya8BjmqT2GCHPwuiMvIAdpnXg0SES3QohR99C9OpF3g2LlSIZn3hPTt0SkfNPgE+tE+3PJnMtKNPMOMgyWIByRJFS9ZhAl+Z3paYhLg3iRJq0uRHfdxFEBwJQpv3WmqaKL5M4lnD5uzVNysvfK8pvxZUM/BdnAc6dPb62BjsySnv45TAbAsk2XOaFSdoldKNN1mw0bqxV8Bz0Ew4b6u7lafsoQgyISINJWkIEYTvGmZzV8AS5j7POyNtRG3Mzwlyt3mMV7EQNZh1fWmFXEoyIfu9k+5dmJkhoHM6qJlttvpKRPU7GThBAWJiN5pZ0s34yH2JdcvPtQ7pY3XWJjPfLxoX1WIRJe/XepzKOE3I5/c7ILcW/OsCFWDH55hFN2lGjNrp6X6DXcMfU+lrreRjx1qMi4l/oqieR7/j/cQQScqtMnIMp4jSmtMii0+Wc7mr9Mg5azrHJ3uwBRbWvtGppM0fuZsdTiBtvZQOEckAz2Zge33ZmMGcb8t+9AFLWH7PJAIQlK3SDzc9V0YAOrQfckZFcIARdy310hB0Pey5MWJHFOEpzffOtLWrde5C6vvNAgQJ29LeGPm7DG/pM="
    # Number of parallel PHPUnit runs.
    # Note: Travis uses 2 CPU cores, but these testsuite processes are often blocked on IO, etc.,
    # so we are still seeing performance improvement when increasing it from 2 to 4.
    - PARALLEL_PHPUNIT_TESTS=4

matrix:
  fast_finish: true
  allow_failures:
    # wdio-testrunner sometimes throws an exception AFTER all tests have succeeded,
    # which leads to exit code 1 (failure). Until the cause is investigated, we don't
    # consider Selenium failures as fatal in Travis (but can always check the log).
    - env: TESTSUITE_TYPE=selenium branch=REL1_31
    - env: TESTSUITE_TYPE=selenium branch=REL1_32
    - env: TESTSUITE_TYPE=selenium branch=REL1_33
    - env: TESTSUITE_TYPE=selenium branch=REL1_34
  include:
    # Linters (phpcs, eslint, etc.)
    - &linter-php-build
      if: NOT branch IN (selenium)
      env: TESTSUITE_TYPE=linter-php
      addons:
      before_script: composer install
      script: composer test

    - &linter-js-build
      if: NOT branch IN (phpunit)
      env: TESTSUITE_TYPE=linter-js
      language: node_js
      node_js: 10
      php: false
      addons:
      before_script: npm install
      script: npm test

    # PHPUnit tests
    - &phpunit-build
      if: NOT branch IN (selenium,troubleshooting,linters)
      env: branch=REL1_31
      script:
        # First run the smallest test without --reuse-db, so that the cloned database tables are created,
        # then run the remaining testsuite with --reuse-db to save time.
        - php tests/phpunit/phpunit.php --use-normal-tables extensions/Moderation/tests/phpunit/ModerationPermissionsTest.php

        # Run all tests in parallel via Fastest.
        # Note: test files are sorted by filesize (from smallest to largest).
        - find extensions/Moderation/tests/phpunit/ -name "*Test.php" -exec ls -1Sr {} + | grep -v selftest | ./extensions/Moderation/vendor/liuggio/fastest/fastest -p "$PARALLEL_PHPUNIT_TESTS" --before="./extensions/Moderation/tests/travis/fastest_init_thread.sh" --preserve-order --verbose "php tests/phpunit/phpunit.php --use-normal-tables --reuse-db {};"

        # NotifyModeratorTest has already been completed without Echo, but it should also be tested with Echo.
        - WITH_ECHO=1 php tests/phpunit/phpunit.php --use-normal-tables --reuse-db extensions/Moderation/tests/phpunit/ModerationNotifyModeratorTest.php

        # Run small benchmarks to detect performance regressions
        # TODO: move this into a separate Travis build stage and do this only on tags/releases.
        - for i in extensions/Moderation/tests/benchmarks/*; do php maintenance/runScript.php $i; done
    - <<: *phpunit-build
      env: branch=REL1_32
    - <<: *phpunit-build
      env: branch=REL1_33
    - <<: *phpunit-build
      env: branch=REL1_34
#    - <<: *phpunit-build
#      env: branch=unknown_branch_will_be_treated_as_master
    - <<: *phpunit-build
      if: branch IN (nightly)
      env: branch=master
      php: nightly
    - <<: *phpunit-build
      if: branch IN (troubleshooting)
      env: branch=REL1_34 FLAKY_TEST="edit in existing page"
      script: ./extensions/Moderation/tests/travis/troubleshoot_flaky_test.sh "${FLAKY_TEST}"

    # Selenium tests
    - &selenium-build
      if: branch IN (master,selenium,travis-sandbox)
      env: TESTSUITE_TYPE=selenium branch=REL1_31
      addons:
          <<: *common-addons
          firefox: latest
          chrome: stable
      script: ( cd extensions/Moderation/tests/selenium && ./node_modules/.bin/wdio wdio.conf.standalone.js --baseUrl 'http://moderation.example.com/mediawiki/' )
      after_script:
        - cat $TRAVIS_BUILD_DIR/parsoid.log
        - sudo cat /var/log/apache2/error.log
    - <<: *selenium-build
      env: TESTSUITE_TYPE=selenium branch=REL1_32
    - <<: *selenium-build
      env: TESTSUITE_TYPE=selenium branch=REL1_33
    - <<: *selenium-build
      env: TESTSUITE_TYPE=selenium branch=REL1_34

cache:
  directories:
    - buildcache
    - parsoid
    - $HOME/.composer/cache

before_script:
  - echo $TESTSUITE_TYPE

  - if [ ${TRAVIS_PHP_VERSION} != "nightly" ]; then phpenv config-rm xdebug.ini; fi
  - phpenv config-add tests/travis/phpconf/php.ini
  - if [ ${TRAVIS_PHP_VERSION:0:1} != "5" ]; then phpenv config-add tests/travis/phpconf/php7.ini; fi
  - php -i

  - if [ ${TESTSUITE_TYPE} = "selenium" ]; then bash -ex ./tests/travis/apache/run_apache.sh; fi
  - if [ ${TESTSUITE_TYPE} = "selenium" ]; then bash -ex ./tests/travis/parsoid/run_parsoid.sh "$branch"; fi
  - bash -ex ./tests/travis/build_mediawiki.sh "$branch"

  - rsync -a --exclude buildcache --exclude mediawiki --exclude .git . mediawiki/extensions/Moderation/
  - cd mediawiki
  - >
      php maintenance/install.php traviswiki admin
      --pass travis
      --dbtype "$DBTYPE"
      --dbname traviswiki
      --dbuser "$DBUSER"
      --dbpass ""
      --scriptpath "/w"
  - echo -en "\n\nrequire_once __DIR__ . '/includes/DevelopmentSettings.php';\n" >> ./LocalSettings.php
  - echo -en "\n\nrequire_once __DIR__ . '/extensions/Moderation/tests/travis/ModerationSettings.php';\n" >> ./LocalSettings.php
  - php -l ./LocalSettings.php
  - mysql -D traviswiki -u "$DBUSER" -e 'DELETE FROM recentchanges;' # Workaround for Extension:CheckUser's updater issue (which is unrelated to Moderation)
  - WITH_ECHO=1 php maintenance/update.php --quick
  - php maintenance/createAndPromote.php "$MEDIAWIKI_USER" "$MEDIAWIKI_PASSWORD" --custom-groups moderator,automoderated
  - if [ ${TESTSUITE_TYPE} = "selenium" ]; then ( cd extensions/Moderation/tests/selenium && npm install ); fi
  - if [ ${TESTSUITE_TYPE} = "phpunit" ]; then ( cd extensions/Moderation && composer install ); fi
